services:
  s1proxy:
    image: caddy:alpine
    container_name: 68_s1_powerrangers_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - s1app

volumes:
  caddy_data:
  caddy_config:
